import { gql } from "@apollo/client";
import client from "../apollo-client";
import Head from 'next/head'

export async function getStaticProps() {
    const { data } = await client.query({
      query: gql`
        {
            getUser {
                id
            }
        }
      `,
    });
    return {
      props: {
        data: data.getUser || {},
      },
   };
}

export default function Home(props) {
  return (
    <>
      <Head>
        <title>Teste</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
    <h1>{props.data.id}</h1>
    </>
  )
}
